language: python


services:
  - docker


os:
  - linux


python:
  - 3.5
  - 3.6
  - pypy3


before_install:
  - docker pull mongo:latest
  - docker run -p 27017:27017 -p 27018:27018 -p 27019:27019 -d mongo:latest


install:
  - pip install hypothesis
  - pip install pytest
  - pip install codecov
  - pip install pytest-cov
  - python setup.py develop


script: py.test --runslow --cov=./cadena/ tests/


after_success:
- codecov

