language: python


services:
- docker


os:
- linux


python:
- 3.5
- 3.6
- pypy3


before_install:
- docker pull mongo:latest
- docker run -p 27017:27017 -p 27018:27018 -p 27019:27019 -d mongo:latest


install:
- pip install hypothesis
- pip install pytest
- pip install codecov
- pip install pytest-cov
- python setup.py develop


script: py.test --runslow --external --cov=./cadena/ tests/


after_success:
- codecov


deploy:
  provider: pypi
  user: magniff
  on:
    branch: develop
    python: "3.6"
  password:
    secure: FBSM0Qn0ravKityvsdflciwaxFvVLVWTqGYbAZ5ahTKtz6F7MQwLXU/ahd6MZWXswprpwLlLMqLqhjMQYZLnjttDlnxLvCKWDNU1TbPxTI60Gn7fCCFwvnTWs7ybSPz0Ohw1VfUxmstZErTUFlDhBiQWzfNC7Ol9RBIdvIoqDmfl5GcLL5lFS0ly9Nel8MtS8tRxhlclFmDDjdrRX7PulC8YIiasDPUiHt9yuxHdbAS4WE4J40Ux/mbRHg53uK6OWHNZNDNykt7eTOmWebc8q+3h3DpjIFrgqGfI8bqs4xpe0GeHfLUIMbeRfWkrL8link1zxahrffk198VLa7Dt72aw9AqhT6pKGkiAKsdAIv6AiF4pyMDUhZOpMJuYtntYObRT2SifgDCTEakClljtizDfLDXbWT5qwyxcfK+b/S+hpMxQXhuZr0UXj2Z/2ekVLonuWNJ26pfvMr7Mv3+IXdbfZL+35L2bIh8n0JOYwMMt1hpPdIqxKvdobtqoqmMH5IeItSyz7ecp0dG1kgcU46y3doDF52UozZge83ILEdupMb1mnPAa2JUHII4HlsOaTjKMMOQX2dqNhI7vNLmRp05lAKN6iTYwxjWseXZmOXNBCisnICORP2ahKcry0v1AzVczbAeTVDLlrRSmaOewrIxaxX7SThuDyDznyRHNU6E=

