language: python


os:
  - linux


python:
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - pypy3


install:
  - pip install codecov
  - pip install pytest-cov
  - python setup.py develop
script: py.test --cov=./snapshot/ tests/


after_success:
- codecov

