# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inode.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='inode.proto',
  package='inode',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x0binode.proto\x12\x05inode\"z\n\x05Inode\x12\x12\n\x07version\x18\x01 \x02(\x05:\x01\x30\x12#\n\x04type\x18\x02 \x02(\x0e\x32\x15.inode.Inode.NodeType\x12\x0b\n\x03tag\x18\x03 \x01(\t\"+\n\x08NodeType\x12\t\n\x05\x43HUNK\x10\x00\x12\x08\n\x04\x46ILE\x10\x01\x12\n\n\x06\x46OLDER\x10\x02')
)



_INODE_NODETYPE = _descriptor.EnumDescriptor(
  name='NodeType',
  full_name='inode.Inode.NodeType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CHUNK', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FILE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FOLDER', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=101,
  serialized_end=144,
)
_sym_db.RegisterEnumDescriptor(_INODE_NODETYPE)


_INODE = _descriptor.Descriptor(
  name='Inode',
  full_name='inode.Inode',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='inode.Inode.version', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='inode.Inode.type', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tag', full_name='inode.Inode.tag', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _INODE_NODETYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=144,
)

_INODE.fields_by_name['type'].enum_type = _INODE_NODETYPE
_INODE_NODETYPE.containing_type = _INODE
DESCRIPTOR.message_types_by_name['Inode'] = _INODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Inode = _reflection.GeneratedProtocolMessageType('Inode', (_message.Message,), dict(
  DESCRIPTOR = _INODE,
  __module__ = 'inode_pb2'
  # @@protoc_insertion_point(class_scope:inode.Inode)
  ))
_sym_db.RegisterMessage(Inode)


# @@protoc_insertion_point(module_scope)
